### ISSUE TITLE
登录认证问题

### ISSUE THREAD

**Issue by neu-liruijia** [leiquan/Agile-Server#1]
在app.js中，中间件的位置需要修改，
`app.use(
  session({
    key: "SSID",
    rolling: true,
    cookie: {
      path: "/",
      httpOnly: true,
      maxAge: 24 * 60 * 60 * 1000, //cookie 有效期1天，默认为 session 的 ttl
      overwrite: true,
      signed: true
    },
    store: redisStore({
      host: env.redis.host,
      port: env.redis.port,
      auth_pass: env.redis.password,
      db: 0 // session 放在 db0,log 放在 db1
    })
  })
);

// 引入自定义的用户认证中间件
let auth = require("./utils/midware/auth");
app.use(auth);`

**Comment by leiquan** [comment]
好的，收到，多谢反馈
